### ISSUE TITLE
Stop using context.Background()

### ISSUE THREAD

**Issue by frostornge** [airbloc/airbloc-go#54]
@therne grpc에서 받은 컨텍스트를 넣어주세요 새로운 컨택스트를 생성해 사용하면 timeout이 된 이후에도 무한정 기다리는 문제가 발생합니다.

Related #44

**Comment by therne** [comment]
## Action Items

- [ ] Add `context` argument to every methods in `Manager`s 😢

**Comment by therne** [comment]
Why @frostornge
